### ISSUE TITLE
Demo support?

### ISSUE THREAD

**Issue by neuromancer** [acoto87/war1#2]
Is support for the [Warcraft 1 demo](https://archive.org/details/WarcraftOrcsHumansDemo) planned for war1?.

**Comment by acoto87** [comment]
I'm targeting the demo file as well, but I need to test it, it may not be working right now, but I want to support it. I will make some tests soon.

**Comment by KuriKai** [comment]
There is a demo with more playable levels found on this cd
https://archive.org/details/MBGAMECD

**Comment by neuromancer** [comment]
Uhm, interesting. Different demo versions (with their differences) are listed here: https://tcrf.net/Proto:Warcraft:_Orcs_%26_Humans

**Comment by acoto87** [comment]
This is good, I'll use it to test my implementation.

I downloaded the .iso for demo version 1.12, and it seems like correct version to target as demo, so I'll look more closely into that one.

Thanks!

**Comment by acoto87** [comment]
I implemented a feature in the game to download the DATA.WAR demo version from here: https://archive.org/download/WarcraftOrcsHumansDemo, I'm closing this issue now.

Thanks!

**Comment by neuromancer** [comment]
Great work! It is a good time to make a release (even 0.1)! Some people (like me), are watching your releases, so this could bring users to test it when you add a new feature.

**Comment by acoto87** [comment]
Yes! I already have it here: https://acoto87.itch.io/war1, feel free to download it and give it a try. Thanks!
