### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by neuromancer** [acoto87/war1#3]
I noticed that a license text in a file / README / source code is missing. Can you also clarify that?

**Comment by acoto87** [comment]
I'm researching a little as for which license to use on the repo, I want it to be MIT, but I need to check the licenses of some of the dependencies.

A proper license file will be up before or at the time of releasing the demo/alpha/pre-alpha (I'm not sure how to call it yet :D) in the following days.

**Comment by acoto87** [comment]
License file has been created.

**Comment by neuromancer** [comment]
Don't forget to change [the headers of the source code](https://github.com/acoto87/war1/search?q=license&unscoped_q=license), which contain references to other licenses (GPL, MIT, etc..)

**Comment by acoto87** [comment]
Sure, will do, thanks!

**Comment by acoto87** [comment]
I put a license for the project that I think will not conflict with licenses of dependencies, I'm closing this issue now.

Thanks!
